### ISSUE TITLE
python -m aiosmb.examples.smbclient smb+ntlm-password://TEST\qgb:xxxx@192.168.8.8

### ISSUE THREAD

**Issue by QGB** [skelsec/aiosmb#14]
```
$ ?

Documented commands:
====================

?                                                           
cd <directory_name>                                         
dcsync  [username=None]                                     It's a suprse tool that will help us later
dcsync  [username=None]                                     It's a suprse tool that will help us later
del <file_name>                                             Removes a file from the remote share
dir                                                         
domaingroups <domain_name>                                  Lists groups in a domain
domains                                                     Lists domain
enumall  [depth=3]                                           Enumerates all shares for all files and folders recursively 
exit                                                        Exit the prompt
get <file_name>                                             Download a file from the remote share to the current folder
getdirsd                                                    
getfilesd <file_name>                                       
groupmembers <domain_name> <group_name>                     Lists members of an arbitrary group
help                                                        
interfaces                                                   Lists all network interfaces of the remote machine 
localgroupmembers <group_name>                              Lists members of a local group
localgroups                                                 Lists local groups
login  [url=None]                                           Connects to the remote machine
logout                                                      
ls                                                          
lsass                                                       
mkdir <directory_name>                                      Creates a directory on the remote share
nodce                                                       Disables automatic share listing on login
parprintnightmare <share> [driverpath='']                    printnightmare bug using the PAR protocol 
printerbug <attacker_ip>                                    Printerbug
printerenumdrivers                                           Enumerates all shares for all files and folders recursively 
printnightmare <share> [driverpath='']                       printnightmare bug using the RPRN protocol 
put <file_name>                                             Uploads a file to the remote share
quit                                                        Exit the prompt
refreshcurdir                                               
reglistusers                                                Saves a registry hive to a file on remote share
regsave <hive_name> <file_path>                             Saves a registry hive to a file on remote share
servicecmdexec <command>                                    Executes a shell command as a service and returns the result
servicecreate <service_name> <command> [display_name=None]  Creates a remote service
servicedeploy <path_to_exec> <remote_path>                  Deploys a binary file from the local system as a service on the remote system
serviceen <service_name>                                    Enables a remote service
services                                                    Lists remote services
sessions                                                    Lists sessions of connected users
shares  [show=True]                                         Lists available shares
taskcmdexec <command>                                        Executes a shell command using the scheduled tasks service
taskdel <task_name>                                         Deletes a scheduled task
taskregister <template_file> [task_name=None]               Registers a new scheduled task
tasks                                                       List scheduled tasks 
use <share_name>                                            selects share to be used
users  [domain=None]                                        List users in domain

```

**Comment by QGB** [comment]
```
$ ls
No share selected!
$ use c
Not logged in! Use "login" first!
Traceback (most recent call last):
  File "/home/qgb/.local/lib/python3.8/site-packages/aiosmb/examples/smbclient.py", line 253, in do_use
    raise err
Exception: Not logged in!
$ login
Traceback (most recent call last):
  File "/home/qgb/.local/lib/python3.8/site-packages/aiosmb/examples/smbclient.py", line 70, in do_login
    raise err
  File "/home/qgb/.local/lib/python3.8/site-packages/aiosmb/connection.py", line 375, in login
    raise err
  File "/home/qgb/.local/lib/python3.8/site-packages/aiosmb/connection.py", line 730, in session_setup
    raise SMBAuthenticationFailed()
aiosmb.commons.exceptions.SMBAuthenticationFailed
Login failed! Reason: 
$
```
