### ISSUE TITLE
services & sessions command in aiosmbclient throw exception

### ISSUE THREAD

**Issue by byt3bl33d3r** [skelsec/aiosmb#2]
Not sure if this is just because it's not finished yet, thought I'd open it in case you weren't aware.
```
$ services
Traceback (most recent call last):
  File "/Users/byt3bl33d3r/.virtualenvs/aiosmb-MxM14DvL/lib/python3.7/site-packages/aiosmb-0.1.1-py3.7.egg/aiosmb/examples/smbclient.py", line 157, in do_services
    async for service in self.machine.list_services():
  File "/Users/byt3bl33d3r/.virtualenvs/aiosmb-MxM14DvL/lib/python3.7/site-packages/aiosmb-0.1.1-py3.7.egg/aiosmb/commons/interfaces/machine.py", line 84, in wrapper
    raise e
  File "/Users/byt3bl33d3r/.virtualenvs/aiosmb-MxM14DvL/lib/python3.7/site-packages/aiosmb-0.1.1-py3.7.egg/aiosmb/commons/interfaces/machine.py", line 81, in wrapper
    async for x in funct(*args, **kwargs):
  File "/Users/byt3bl33d3r/.virtualenvs/aiosmb-MxM14DvL/lib/python3.7/site-packages/aiosmb-0.1.1-py3.7.egg/aiosmb/commons/interfaces/machine.py", line 222, in list_services
    async for service in self.servicemanager.list():
  File "/Users/byt3bl33d3r/.virtualenvs/aiosmb-MxM14DvL/lib/python3.7/site-packages/aiosmb-0.1.1-py3.7.egg/aiosmb/dcerpc/v5/interfaces/servicemanager.py", line 58, in list
    resp = await scmr.hREnumServicesStatusW(self.dce, self.handle)
  File "/Users/byt3bl33d3r/.virtualenvs/aiosmb-MxM14DvL/lib/python3.7/site-packages/aiosmb-0.1.1-py3.7.egg/aiosmb/dcerpc/v5/scmr.py", line 1278, in hREnumServicesStatusW
    resp = await dce.request(enumServicesStatus)
  File "/Users/byt3bl33d3r/.virtualenvs/aiosmb-MxM14DvL/lib/python3.7/site-packages/aiosmb-0.1.1-py3.7.egg/aiosmb/dcerpc/v5/rpcrt.py", line 863, in request
    answer = await self.recv()
  File "/Users/byt3bl33d3r/.virtualenvs/aiosmb-MxM14DvL/lib/python3.7/site-packages/aiosmb-0.1.1-py3.7.egg/aiosmb/dcerpc/v5/rpcrt.py", line 1436, in recv
    response_data = await self._transport.recv(MSRPCRespHeader._SIZE)
  File "/Users/byt3bl33d3r/.virtualenvs/aiosmb-MxM14DvL/lib/python3.7/site-packages/aiosmb-0.1.1-py3.7.egg/aiosmb/dcerpc/v5/transport/smbtransport.py", line 38, in recv
    t = await self.pipe_reader.read(-1)
  File "/Users/byt3bl33d3r/.virtualenvs/aiosmb-MxM14DvL/lib/python3.7/site-packages/aiosmb-0.1.1-py3.7.egg/aiosmb/filereader.py", line 152, in read
    data = await self.__read(self.file.size - self.position, self.position)
  File "/Users/byt3bl33d3r/.virtualenvs/aiosmb-MxM14DvL/lib/python3.7/site-packages/aiosmb-0.1.1-py3.7.egg/aiosmb/filereader.py", line 41, in __read
    data, remaining = await self.connection.read(self.share.tree_id, self.file.file_id, offset = offset, length = size)
  File "/Users/byt3bl33d3r/.virtualenvs/aiosmb-MxM14DvL/lib/python3.7/site-packages/aiosmb-0.1.1-py3.7.egg/aiosmb/connection.py", line 608, in read
    raise SMBGenericException()
aiosmb.commons.exceptions.SMBGenericException
```

**Comment by byt3bl33d3r** [comment]
Target is a Windows 2019 DC, connected with domain admin creds.

**Comment by skelsec** [comment]
it took like a day to resolve this issue, new commit will handle it.
basically the NTSTATUS_PENDING error was treated as an actual error message and got propagated to the caller. Who was not really expecting that to happen.
In the new version there is a basic resolution for this, !however! handling pending messages is 
1. not doumented
2. quite complex
so I just provided a simple but extensible solution that works. might need to be refined later
